name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
        env:
          OPEN_WEATHER_KEY: ${{ secrets.OPEN_WEATHER_KEY }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          ACCU_WEATHER_KEY: ${{ secrets.ACCU_WEATHER_KEY }}

  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check fmt
        run: cargo fmt --check
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Check spelling
        uses: crate-ci/typos@master
